---
- name: Add new disk 
  community.vmware.vmware_guest_disk:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    datacenter: "{{ datacenter_name }}"
    validate_certs: False
    name: "{{ vm_name }}"
    disk:
      - size_gb: 10
        type: thin
        datastore: "{{ datastore_name }}"
        state: present
        scsi_controller: 2
        unit_number: 2
        scsi_type: 'paravirtual'
        disk_mode: 'persistent'
