---
- name: Add existing disk
  community.vmware.vmware_guest_disk:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    datacenter: "{{ datacenter_name }}"
    name: "{{ vm_name }}"
    validate_certs: False
    disk:
       - filename: "[{{ datastore_name }}] {{ path }}/{{ disk_name }}"
         unit_number: 2
         state: present
         scsi_controller: 2
         size: 10Gb
