---
- name: Check if disk exist
  community.vmware.vsphere_file:
    host: "{{ dialog_param_vcenter_hostname }}"
    username: "{{ dialog_param_vcenter_username }}"
    password: "{{ dialog_param_vcenter_password }}"
    datacenter: "{{ dialog_param_datacenter_name }}"
    datastore: "{{ dialog_param_datastore_name }}"
    dialog_param_path: "{{ dialog_param_path }}/{{ dialog_param_disk_name }}"
    state: file
    validate_certs: false
  ignore_errors: true
  register: status


- name: Set variable disk_exist to false
  set_fact:
    disk_exist: "false"
  when: status.status == 404

- name: Set variable disk_exist to true
  set_fact:
    disk_exist: "true" 
  when: status.status == 200
